language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - CODE_STYLE=true
    - php: 8.0
    - php: 8.1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --no-progress --no-suggest --no-interaction --prefer-dist
  - if [[ $CODE_STYLE == 'true' ]]; then composer install --working-dir=tools/php-cs-fixer; fi

script:
  - php vendor/bin/phpunit
  - php vendor/bin/behat
  - if [[ $CODE_STYLE == 'true' ]]; then php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run -v; fi
